name: Auto Update IBS Special Sports

on:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিট পর পর
  workflow_dispatch:        # ম্যানুয়াল রানের জন্য বাটন

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # রাইট পারমিশন

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Node.js 24 সাপোর্ট করার জন্য v4 এ আপডেট করা হলো

      - name: Set up Python
        uses: actions/setup-python@v5 # Python-এর লেটেস্ট ভার্সনে আপডেট করা হলো
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install requests pytz

      - name: Run Sports Scraper
        run: python crichd.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # ব্রাঞ্চ পুল করা
          git pull origin M3u8 --rebase || true
          
          git add "Crichd playlist.m3u"
          
          # পরিবর্তন চেক করুন: কোনো পরিবর্তন থাকলে কমিট হবে, অন্যথায় স্কিপ করবে
          git diff --staged --quiet || git commit -m "Crichd Sports Update: $(date)"
          
          # পুশ করা
          git push origin M3u8 --force
          
